/*
*qtResourceDef.h
*/

#ifndef __QT_RESOURCE_DEF_H__
#define	__QT_RESOURCE_DEF_H__

enum
{
	STOCK_REAL_WIDGET_IDEX_CODE = 0,
	STOCK_REAL_WIDGET_IDEX_NAME,
	STOCK_REAL_WIDGET_IDEX_CLOSE,
	STOCK_REAL_WIDGET_IDEX_OPEN,
	STOCK_REAL_WIDGET_IDEX_HIGH,
	STOCK_REAL_WIDGET_IDEX_LOW,
	STOCK_REAL_WIDGET_IDEX_MA10,
	STOCK_REAL_WIDGET_IDEX_RSI7,
	STOCK_REAL_WIDGET_IDEX_DATE,
	STOCK_REAL_WIDGET_IDEX_NUM
};


#define STOCK_REAL_WIDGET_TEXT_DFT		"--"
#define STOCK_REAL_WIDGET_LAB_CLOSE		"收盘价"
#define STOCK_REAL_WIDGET_LAB_OPEN		"开盘价"
#define STOCK_REAL_WIDGET_LAB_HIGH		"最高价"
#define STOCK_REAL_WIDGET_LAB_LOW		"最低价"
#define STOCK_REAL_WIDGET_LAB_MA10		"MA10"
#define STOCK_REAL_WIDGET_LAB_RSI7		"RSI7"
#define STOCK_REAL_WIDGET_LAB_DATE		"日期"


#endif // !__QT_RESOURCE_DEF_H__
