/*
*qtResourceDef.h
*/

#ifndef __QT_RESOURCE_DEF_H__
#define	__QT_RESOURCE_DEF_H__

enum
{
	STOCK_REAL_WIDGET_IDEX_CODE = 0,
	STOCK_REAL_WIDGET_IDEX_NAME,
	STOCK_REAL_WIDGET_IDEX_CLOSE,
	STOCK_REAL_WIDGET_IDEX_OPEN,
	STOCK_REAL_WIDGET_IDEX_HIGH,
	STOCK_REAL_WIDGET_IDEX_LOW,
	STOCK_REAL_WIDGET_IDEX_MA10,
	STOCK_REAL_WIDGET_IDEX_RSI7,
	STOCK_REAL_WIDGET_IDEX_DATE,
	STOCK_REAL_WIDGET_IDEX_NUM
};


#define STOCK_REAL_WIDGET_TEXT_DFT		"--"
#define STOCK_REAL_WIDGET_LAB_CLOSE		"收盘价"
#define STOCK_REAL_WIDGET_LAB_OPEN		"开盘价"
#define STOCK_REAL_WIDGET_LAB_HIGH		"最高价"
#define STOCK_REAL_WIDGET_LAB_LOW		"最低价"
#define STOCK_REAL_WIDGET_LAB_MA10		"MA10"
#define STOCK_REAL_WIDGET_LAB_RSI7		"RSI7"
#define STOCK_REAL_WIDGET_LAB_DATE		"日期"


#define STOCK_TRACE_WIDGET_LAB_WAIT_BUY		"等待买入股票"
#define STOCK_TRACE_WIDGET_LAB_WAIT_SELL	"等待卖出股票"

enum
{
	STOCK_TRACE_WIDGET_TREE_WAITBUY_INDEX_CODE_NAME = 0,
	STOCK_TRACE_WIDGET_TREE_WAITBUY_INDEX_RAISE_BALANCE,
	STOCK_TRACE_WIDGET_TREE_WAITBUY_INDEX_REACH_HIGH,
	STOCK_TRACE_WIDGET_TREE_WAITBUY_INDEX_WAIT_RSI,
	STOCK_TRACE_WIDGET_TREE_WAITBUY_INDEX_WAIT_BUY,
	STOCK_TRACE_WIDGET_TREE_WAITBUY_INDEX_NUM,
};

#define STOCK_TRACE_WIDGET_TREE_WAITBUY_NAME_CODE_NAME			"股票名称"
#define STOCK_TRACE_WIDGET_TREE_WAITBUY_NAME_RAISE_BALANCE		"横盘3周期"
#define STOCK_TRACE_WIDGET_TREE_WAITBUY_NAME_REACH_HIGH			"创新高"
#define STOCK_TRACE_WIDGET_TREE_WAITBUY_NAME_WAIT_RSI			"RSI破线"
#define STOCK_TRACE_WIDGET_TREE_WAITBUY_NAME_WAIT_BUY			"自动买入"


enum
{
	STOCK_TRACE_WIDGET_TREE_WAITSELL_INDEX_CODE_NAME = 0,
	STOCK_TRACE_WIDGET_TREE_WAITSELL_INDEX_MA10,
	STOCK_TRACE_WIDGET_TREE_WAITSELL_INDEX_EARNS,
	STOCK_TRACE_WIDGET_TREE_WAITSELL_INDEX_RSI,
	STOCK_TRACE_WIDGET_TREE_WAITSELL_INDEX_CUT_BACK,
	STOCK_TRACE_WIDGET_TREE_WAITSELL_INDEX_WAIT_SELL,
	STOCK_TRACE_WIDGET_TREE_WAITSELL_INDEX_NUM,
};

#define STOCK_TRACE_WIDGET_TREE_WAITSELL_NAME_CODE_NAME		"股票名称"
#define STOCK_TRACE_WIDGET_TREE_WAITSELL_NAME_MA10			"MA10/CLOSE"
#define STOCK_TRACE_WIDGET_TREE_WAITSELL_NAME_EARNS			"BUY/CLOSE/收益"
#define STOCK_TRACE_WIDGET_TREE_WAITSELL_NAME_RSI			"RSI"
#define STOCK_TRACE_WIDGET_TREE_WAITSELL_NAME_CUT_BACK		"买入后HIGH/CLOSE/回落比"
#define STOCK_TRACE_WIDGET_TREE_WAITSELL_NAME_WAIT_SELL		"自动卖出"
#endif // !__QT_RESOURCE_DEF_H__
