/*stockConfigDef.h
*
*/

#ifndef __STOCK_CONFIG_DEF_H__
#define __STOCK_CONFIG_DEF_H__

#include <global.h>
#define STOCK_CONFIG_NAME_MAX		STOCK_AUTO_SAVE_DIR_MAX_SIZE

#define XXX_WORK

/*默认配置*/
#ifdef XXX_WORK
#define STOCKAUTO_CONFIG_PYTHON_MODULEDIR_DFT		"E:\\self\\stock\\src\\py"
#else
#define STOCKAUTO_CONFIG_PYTHON_MODULEDIR_DFT		"E:\\work\\stock\\StockAuto\\src\\py"
#endif 
#define	STOCKAUTO_CONFIG_PYTHON_KLINE_MODULE_DFT	PYTHON_MOUDLE_WEEK_KLINE
#ifdef XXX_WORK
#define	STOCKAUTO_CONFIG_PYTHON_UPDATE_DIR_DFT			"E:\\self\\stock\\data"
#else
#define STOCKAUTO_CONFIG_PYTHON_UPDATE_DIR_DFT		"E:\\work\\stock\\StockAuto\\data"
#endif
#define	STOCKAUTO_CONFIG_PYTHON_DB_STOCKLIST_DFT		"stockList.db"
#define	STOCKAUTO_CONFIG_PYTHON_DB_STOCKKLINE_DFT		"kline.db"

struct STOCKAUTO_CONFIG_PYTHON
{
	char moduleDir[STOCK_CONFIG_NAME_MAX];			/*python 模块路径*/
	char klineModule[STOCK_CONFIG_NAME_MAX];		/*python K线更新模块名称*/
	char updateDir[STOCK_CONFIG_NAME_MAX];			/*python 获取数据更新路径*/
	char dbStockList[STOCK_CONFIG_NAME_MAX];		/*python 获取股票列表数据库名称*/
	char dbStockKLine[STOCK_CONFIG_NAME_MAX];		/*python 获取股票KLine数据库名称*/
};

#define STOCKAUTO_CONFIG_DATA_DATADIR_DFT			STOCKAUTO_CONFIG_PYTHON_UPDATE_DIR_DFT
#define	STOCKAUTO_CONFIG_DATA_LIST_FILENAME_DFT		STOCKAUTO_CONFIG_PYTHON_DB_STOCKLIST_DFT
#define	STOCKAUTO_CONFIG_DATA_KLINE_FILENAME_DFT	STOCKAUTO_CONFIG_PYTHON_DB_STOCKKLINE_DFT
#define	STOCKAUTO_CONFIG_DATA_TRACELOG_FILENAME_DFT	"tracelog.db"

struct STOCKAUTO_CONFIG_DATA
{
	char dataDir[STOCK_CONFIG_NAME_MAX];
	char listFileName[STOCK_CONFIG_NAME_MAX];
	char klineFileName[STOCK_CONFIG_NAME_MAX];
	char tracelogFileName[STOCK_CONFIG_NAME_MAX];
};

struct STOCKAUTO_CONFIG_TRACE
{
	float		fRaisePercent;
	int			raiseBalances;
	int			reachHighRanges;
	float		fHighLostPercent;
	int			raiseBalanceWaits;
	float		fVolumePercentBuy;
	int			rsiBuyWaits;
	float		fRsiBuy;
	float		fRsiSell;
	float		rsiSellWaits; 
	float		fCutLossPercent;
	float		fCutLossAfterTop;
};

#define STOCKAUTO_CONFIG_TRACE_RAISE_PERCENT_DFT		0.9
#define STOCKAUTO_CONFIG_TRACE_RAISE_BALANCES_DFT		3
#define STOCKAUTO_CONFIG_TRACE_REAHHIGH_RANGES_DFT		60
#define STOCKAUTO_CONFIG_TRACE_HIGH_LOSTPERCENT_DFT		13
#define	STOCKAUTO_CONFIG_TRACE_RAISEBALANCE_WAITS_DFT	6
#define STOCKAUTO_CONFIG_TRACE_VOLUME_PERCENT_BUY_DFT	100
#define STOCKAUTO_CONFIG_TRACE_RSI_BUY_WAIT_DFT			5
#define STOCKAUTO_CONFIG_TRACE_RSI_BUY_DFT				75
#define STOCKAUTO_CONFIG_TRACE_RSI_SELL_DFT				70
#define	STOCKAUTO_CONFIG_TRACE_RSI_SELL_WAITS_DFT		3
#define	STOCKAUTO_CONFIG_TRACE_CUTLOSS_PERCENT_DFT		0.7
#define	STOCKAUTO_CONFIG_TRACE_CUTLOSS_AFTERTOP_DFT		30

struct STOCKAUTO_CONFIG
{
	STOCKAUTO_CONFIG_PYTHON		configPython;
	STOCKAUTO_CONFIG_DATA		configData;
	STOCKAUTO_CONFIG_TRACE		configTrace;
};

#define	STOCKAUTO_CONFIG_PYTHON_GROUP_NAME			"python"
#define	STOCKAUTO_CONFIG_PYTHON_GROUP_MODULE_DIR	"moduleDir"
#define	STOCKAUTO_CONFIG_PYTHON_GROUP_KLINE_MODULE	"klineModule"
#define	STOCKAUTO_CONFIG_PYTHON_GROUP_UPDATE_DIR	"updateDir"
#define	STOCKAUTO_CONFIG_PYTHON_GROUP_DB_STOCKLIST	"dbStockList"
#define	STOCKAUTO_CONFIG_PYTHON_GROUP_DB_STOCKKLINE	"dbStockKLine"

#define	STOCKAUTO_CONFIG_DATA_GROUP_NAME			"data"
#define	STOCKAUTO_CONFIG_DATA_GROUP_DATA_DIR		"dataDir"
#define	STOCKAUTO_CONFIG_DATA_GROUP_STOCKLIST_FILE	"stockListFile"
#define	STOCKAUTO_CONFIG_DATA_GROUP_STOCKKLINE_FILE	"stockKLineFile"
#define	STOCKAUTO_CONFIG_DATA_GROUP_TRACELOG_FILE	"traceLogFile"

#define	STOCKAUTO_CONFIG_TRACE_GROUP_NAME				"trace"
#define	STOCKAUTO_CONFIG_TRACE_GROUP_RAISE_PERCENT		"raisePercent"
#define	STOCKAUTO_CONFIG_TRACE_GROUP_RAISE_BALANCES		"raiseBalances"
#define	STOCKAUTO_CONFIG_TRACE_GROUP_HIGH_RANGES		"highRanges"
#define STOCKAUTO_CONFIG_TRACE_GROUP_HIGH_LOSTPERCENT	"highLostPercent"
#define STOCKAUTO_CONFIG_TRACE_GROUP_RAISEBALANCE_WAITS	"raiseBalanceWaits"
#define STOCKAUTO_CONFIG_TRACE_GROUP_VOLUME_PERCENT_BUY	"volumePercentBuy"
#define	STOCKAUTO_CONFIG_TRACE_GROUP_RSI_BUYWAITS		"rsiBuyWaits"
#define	STOCKAUTO_CONFIG_TRACE_GROUP_RSI_BUY			"rsiBuy"
#define	STOCKAUTO_CONFIG_TRACE_GROUP_RSI_SELL			"rsiSell"
#define	STOCKAUTO_CONFIG_TRACE_GROUP_RSI_SELLWAITS		"rsiSellWaits"
#define	STOCKAUTO_CONFIG_TRACE_GROUP_CUTLOSS_PERCENT	"cutLossPercent"
#define	STOCKAUTO_CONFIG_TRACE_GROUP_CUTLOSS_AFTERTOP	"cutLossAfterTop"
#endif // !__STOCK_CONFIG_DEF_H__
